[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PostgreSQL 教程"
authors = [{name = "YCH", email = "chnyyk@gmail.com"}]
dynamic = ["version", "description"]
